version: "3.6"

services:
 sut:
  build: ./test
  user: root
  volumes:
    - "./:/root/.minetest/worlds/world/worldmods/modgen/"
    - "world:/root/.minetest/worlds/world"
  ports:
    - "30000:30000/udp"

volumes:
  world: {}